language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - master

script:
  - npm run all_tests
  - npm run build --aot --prod

deploy:
  provider: heroku
  api_key:
    secure: "0f5aad02-bf4f-404e-9822-fc6215605da1"
  app: app-jira